#!/usr/bin/env ruby

require 'capybara'
require 'capybara/webkit'

include Capybara::DSL
Capybara.default_driver = :webkit
page.driver.block_unknown_urls
page.driver.allow_url "https://www.mrlodge.com/*"
#page.driver.block_unknown_urls
visit "https://www.mrlodge.com/search/"
fill_in('mrl_ft_sterm', :with => 'Dingolfinger')
fill_in('mrl_ft_rent_to', :with => '1400')
#select('1.5', :from => 'mrl_ft_rooms_from')
select('***', :from => 'mrl_ft_category')
click_on('Show offers')


all("div.mrl-ft-list-row").each do |offer|
    title = offer.find("h3.mrl-headline").text
    id = offer["data-uid".to_sym]
    availability = offer.find("span.mrl-avail").text
    distance = offer.find("span.mrl-distance").text
    is_new = offer.has_css?("span.mrl-ft-lstat")
    rent = offer.find("dt.mrl-rent").text
    size = offer.find("dt.mrl-area").text
    stars = offer.all(".i i_star").size

    if (not (availability.include? "6-" or availability.include? " 6 months"))
	    puts ""
	    puts ((is_new) ? "***NEW*** " : "") + title + " [" + rent + "]"
	    puts availability
	    puts stars
	    puts size
	    puts distance
	    puts "https://www.mrlodge.com/search/detailed-view/"+id
	end
end
